#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
from urllib.request import urlopen, Request

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "generated"
OUT.mkdir(exist_ok=True)

BASE = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash"

UPSTREAM = {
    "AI.yaml": [
        f"{BASE}/OpenAI/OpenAI.yaml",
        f"{BASE}/Claude/Claude.yaml",
        f"{BASE}/Gemini/Gemini.yaml",
    ],
    "YouTube.yaml": [f"{BASE}/YouTube/YouTube.yaml"],
    "Netflix.yaml": [f"{BASE}/Netflix/Netflix.yaml"],
    "Telegram.yaml": [f"{BASE}/Telegram/Telegram.yaml"],
    "Github.yaml": [f"{BASE}/GitHub/GitHub.yaml"],
    "Social.yaml": [
        f"{BASE}/Facebook/Facebook.yaml",
        f"{BASE}/Instagram/Instagram.yaml",
        f"{BASE}/Reddit/Reddit.yaml",
    ],
    "Cloud.yaml": [f"{BASE}/Cloudflare/Cloudflare.yaml"],
    "Proxy.yaml": [f"{BASE}/Proxy/Proxy.yaml"],
}

EXTRA = {
    "AI.yaml": [
        "DOMAIN-SUFFIX,chatgpt.com",
        "DOMAIN-SUFFIX,openai.com",
        "DOMAIN-SUFFIX,oaistatic.com",
        "DOMAIN-SUFFIX,oaiusercontent.com",
        "DOMAIN-SUFFIX,files.oaiusercontent.com",
        "DOMAIN-SUFFIX,claude.ai",
        "DOMAIN-SUFFIX,anthropic.com",
        "DOMAIN-SUFFIX,gemini.google.com",
        "DOMAIN-SUFFIX,perplexity.ai",
        "DOMAIN-SUFFIX,openrouter.ai",
    ],
    "X.yaml": [
        "DOMAIN-SUFFIX,x.com",
        "DOMAIN-SUFFIX,twitter.com",
        "DOMAIN-SUFFIX,t.co",
        "DOMAIN-SUFFIX,twimg.com",
        "DOMAIN-SUFFIX,abs.twimg.com",
        "DOMAIN-SUFFIX,pbs.twimg.com",
        "DOMAIN-SUFFIX,video.twimg.com",
        "DOMAIN-SUFFIX,api.x.com",
        "DOMAIN-SUFFIX,ads-api.x.com",
    ],
    "Finance-Pay.yaml": [
        "DOMAIN-SUFFIX,paypal.com",
        "DOMAIN-SUFFIX,paypalobjects.com",
        "DOMAIN-SUFFIX,wise.com",
        "DOMAIN-SUFFIX,stripe.com",
        "DOMAIN-SUFFIX,stripe.network",
        "DOMAIN-SUFFIX,binance.com",
        "DOMAIN-SUFFIX,coinbase.com",
    ],
    "Finance-Info.yaml": [
        "DOMAIN-SUFFIX,tradingview.com",
        "DOMAIN-SUFFIX,investing.com",
        "DOMAIN-SUFFIX,coingecko.com",
        "DOMAIN-SUFFIX,coinmarketcap.com",
        "DOMAIN-SUFFIX,glassnode.com",
        "DOMAIN-SUFFIX,defillama.com",
    ],
    "Cloud.yaml": [
        "DOMAIN-SUFFIX,workers.dev",
        "DOMAIN-SUFFIX,pages.dev",
        "DOMAIN-SUFFIX,vercel.com",
        "DOMAIN-SUFFIX,vercel.app",
        "DOMAIN-SUFFIX,oracle.com",
        "DOMAIN-SUFFIX,azure.com",
    ],
}


def fetch_payload(url: str) -> list[str]:
    req = Request(url, headers={"User-Agent": "clash-rules-sync"})
    with urlopen(req, timeout=30) as resp:
        text = resp.read().decode("utf-8")
    out: list[str] = []
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("- "):
            item = s[2:].strip()
            if item and not item.startswith("#"):
                out.append(item)
    return out


def write_yaml(name: str, items: list[str]) -> None:
    seen = set()
    ordered = []
    for item in items:
        if item not in seen:
            seen.add(item)
            ordered.append(item)
    body = ["# Generated by scripts/sync_rules.py", "payload:"]
    body += [f"  - {item}" for item in ordered]
    (OUT / name).write_text("\n".join(body) + "\n", encoding="utf-8")


def main() -> None:
    names = sorted(set(UPSTREAM) | set(EXTRA))
    for name in names:
        items: list[str] = []
        for url in UPSTREAM.get(name, []):
            items.extend(fetch_payload(url))
        items.extend(EXTRA.get(name, []))
        write_yaml(name, items)


if __name__ == "__main__":
    main()
